baseURL = "http://eldo.remaker.com"
languageCode = "en-us"
title = "1975 Cadillac Eldorado Convertible"
theme = "ananke"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true
copyright = "Phillip Remaker, except where noted, 1975 -"

[params]
  favicon = "/images/favicon.ico"
  site_logo = ""
  description = "Dedicated to the 1975 Cadillac Eldorado Convertible"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-moon-grey"
  featured_image = "/images/caddy1.jpg"
  recent_posts_number = 5
